version: '2'

services:
  opbadges:
    container_name: opbadges
    image: node:9.1.0-wheezy
    ports:
      - 3000:3000
    volumes:
      - "./:/usr/src/app"
    working_dir: /usr/src/app
    command: npm run dev
    restart: "no"
      