version: '2'

services:
  opbadges:
    container_name: opbadges
    image: node:9.1.0-wheezy
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 3000:3000
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
    tty: true
    command: npm run dev
