version: '2'

services:
  db:
    container_name: opbadges_db
    image: mariadb
    restart: on-failure
    ports: 
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: openbadges
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_PASSWORD: toor

  opbadges:
    container_name: opbadges
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
    restart: on-failure
    links:
      - db
      